spring.application.name=curriculovt

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/curriculovt
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

mercado_pago.webhook.secret=79a0db1a405292c3871cd849ea56d7a627ab287e936a450482a6e661f5eeb9052
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api